package implementation;

import dao.KhachHang_DAO;
import entity.KhachHang;
import service.KhachHangService;

import java.rmi.RemoteException;
import java.rmi.server.UnicastRemoteObject;
import java.util.List;

public class KhachHangServiceImpl extends UnicastRemoteObject implements KhachHangService {
    private KhachHang_DAO khachHang_DAO;

    public KhachHangServiceImpl(KhachHang_DAO khachHang_DAO) throws RemoteException {
        this.khachHang_DAO = khachHang_DAO;
    }

    @Override
    public List<KhachHang> getAllKhachHang() throws RemoteException {
        return khachHang_DAO.getAllKhachHang();
    }

    @Override
    public String getAutoGeneratedId() throws RemoteException {
        return khachHang_DAO.getAutoGeneratedId();
    }

    @Override
    public boolean create(KhachHang khachHang) throws RemoteException {
        return khachHang_DAO.create(khachHang);
    }

    @Override
    public boolean update(KhachHang kh) throws RemoteException {
        return khachHang_DAO.update(kh);
    }

    @Override
    public boolean updateSoSDT(String maKH, String sdt) throws RemoteException {
        return khachHang_DAO.updateSoSDT(maKH, sdt);
    }

    @Override
    public boolean delete(String maKH) throws RemoteException {
        return khachHang_DAO.delete(maKH);
    }

    @Override
    public KhachHang getKhachHangTheoMaKH(String maKH) throws RemoteException {
        return khachHang_DAO.getKhachHangTheoMaKH(maKH);
    }

    @Override
    public KhachHang getKHTheoCCCD(String soCCCD) throws RemoteException {
        return khachHang_DAO.getKHTheoCCCD(soCCCD);
    }

    @Override
    public KhachHang getKhachHangTheoSDT(String sdt) throws RemoteException {
        return khachHang_DAO.getKhachHangTheoSDT(sdt);
    }
} 