package dao;

import entity.KhachHang;
import jakarta.persistence.EntityManager;
import jakarta.persistence.EntityTransaction;

import java.util.ArrayList;

public class KhachHang_DAO {
    private final EntityManager em;
    private final EntityTransaction transaction;

    public KhachHang_DAO(EntityManager em) {
        this.em = em;
        this.transaction = em.getTransaction();
    }

    public ArrayList<KhachHang> getAllKhachHang() {
        String sql = "Select * from KhachHang";
        return (ArrayList<KhachHang>) em.createNativeQuery(sql, KhachHang.class).getResultList();
    }

    public String getAutoGeneratedId() {
        return (String) em.createNativeQuery("SELECT [dbo].[auto_idkh]()")
                .getSingleResult();
    }

    public void creat(KhachHang khachHang) {
        try {
            String generatedId = getAutoGeneratedId();
            khachHang.setMaKH(generatedId);

            transaction.begin();
            em.persist(khachHang);
            transaction.commit();

//            System.out.println("Lưu khách hàng thành công với mã: " + generatedId);
        } catch (Exception e) {
            if (transaction.isActive()) {
                transaction.rollback();
            }
            e.printStackTrace();
            throw e;
        }
    }

    public boolean update(KhachHang kh) {
        return executeTransaction(() -> em.merge(kh));
    }

    public boolean updateSoSDT (String maKH, String sdt) {
        return executeTransaction(() -> {
            KhachHang kh = getKhachHangTheoMaKH(maKH);
            kh.setSdt(sdt);
        });
    }

    public boolean delete(String maKH) {
        return executeTransaction(() -> {
            KhachHang kh = getKhachHangTheoMaKH(maKH);
            em.remove(kh);
        });
    }

    public KhachHang getKhachHangTheoMaKH(String maKH) {
        String sql = "Select * from KhachHang where ma_kh = ?";
        return (KhachHang) em.createNativeQuery(sql, KhachHang.class).setParameter(1, maKH).getSingleResult();
    }

    public KhachHang getKHTheoCCCD(String soCCCD) {
        String sql = "Select * from KhachHang where socccd = ?";
        return (KhachHang) em.createNativeQuery(sql, KhachHang.class).setParameter(1, soCCCD).getSingleResult();
    }

    public KhachHang getKhachHangTheoSDT(String sdt) {
        String sql = "Select * from KhachHang where sdt = ?";
        return (KhachHang) em.createNativeQuery(sql, KhachHang.class).setParameter(1, sdt).getSingleResult();
    }

    private boolean executeTransaction(Runnable action) {
        try {
            transaction.begin();
            action.run();
            transaction.commit();
            return true;
        } catch (Exception e) {
            if (transaction.isActive()) {
                transaction.rollback();
            }
            e.printStackTrace();
            return false;
        }
    }

    public KhachHang getKhachHang(String maKH) {
        return em.find(KhachHang.class, maKH);
    }
}


